version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    working_dir: /var/www
    tty: true
    volumes:
      - ./api:/var/www
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 3000:3000
    depends_on: # コンテナ間の依存関係(先に起動するコンテナのサービス名) PHP->Nginxの順でコンテナを起動
      - api
    volumes:
      - ./api:/var/www
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    platform: linux/x86_64 # M1 mac用
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: game_release_db
      MYSQL_USER: game_release
      MYSQL_PASSWORD: game_release_pass
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - game_release:/var/lib/mysql
  py:
    # restart: always
    build:
      context: .
      dockerfile: ./docker/py/Dockerfile
    container_name: 'py'
    working_dir: '/var/www/python'
    tty: true
    volumes:
      - ./:/var/www/python
    networks:
     app_net: 
      ipv4_address: 172.28.1.5 # <- 固定IPに指定
    extra_hosts: 
      - "host.docker.internal:host-gateway" #<- containerの中からアクセスできるようにhostのIPを渡す

#ネットワーク設定
networks:
  app_net: # <-ここはどんな名前でも大丈夫
    driver: bridge
    name: app_net
    ipam:
      config:
        - subnet: 172.28.1.0/24

#ネットワーク設定
networks:
  app_net: # <-ここはどんな名前でも大丈夫
    driver: bridge
    name: app_net
    ipam:
      config:
        - subnet: 172.28.1.0/24

volumes:
  game_release:
